-- Ledger schema for Supabase (PostgreSQL 15+).
-- Run once in the Supabase SQL editor. Safe to re-run (idempotent where possible).
--
-- Security model
--   * Every row belongs to a user (user_id → auth.users). RLS allows each signed-in user
--     to see and change only their own rows; the `anon` role gets no access at all.
--   * The app calls PostgREST with the *user's* JWT (never the service-role key), so
--     RLS is enforced by the database even if the app has a bug.
--   * IDs are UUIDs generated by the database (gen_random_uuid) — unguessable and
--     type-checked (a malformed id is rejected before it reaches a query plan).
--   * A transaction can only reference a category owned by the same user and of the
--     same type (composite foreign key), so data can't leak across users via FKs.

-- ── Tables ────────────────────────────────────────────────────────────────────

create table if not exists public.categories (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null default auth.uid() references auth.users (id) on delete cascade,
  type        text not null check (type in ('income', 'expense')),
  name        text not null check (char_length(btrim(name)) between 1 and 40),
  icon        text not null check (char_length(icon) between 1 and 16),
  color       text not null check (color ~ '^#[0-9a-fA-F]{6}$'),
  sort_order  integer not null default 0,
  created_at  timestamptz not null default now(),
  -- target of the composite FK below
  unique (id, user_id, type)
);

create table if not exists public.transactions (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid not null default auth.uid() references auth.users (id) on delete cascade,
  date         date not null,
  type         text not null check (type in ('income', 'expense')),
  category_id  uuid not null,
  amount       numeric(14, 2) not null check (amount > 0 and amount <= 1000000000000),
  description  text not null check (char_length(btrim(description)) between 1 and 200),
  note         text not null default '' check (char_length(note) <= 500),
  tags         text[] not null default '{}' check (cardinality(tags) <= 20),
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  -- same owner + same type as the category; blocks deleting a category that is in use
  foreign key (category_id, user_id, type)
    references public.categories (id, user_id, type) on delete restrict
);

create index if not exists transactions_user_date_idx on public.transactions (user_id, date desc, created_at desc);
create index if not exists transactions_category_idx  on public.transactions (category_id);
create index if not exists categories_user_idx        on public.categories (user_id, sort_order);

-- One settings row per user.
create table if not exists public.settings (
  user_id                 uuid primary key default auth.uid() references auth.users (id) on delete cascade,
  currency                text not null default 'THB' check (currency ~ '^[A-Z]{3}$'),
  currency_symbol         text not null default '฿' check (char_length(currency_symbol) between 1 and 4),
  locale                  text not null default 'th-TH',
  monthly_budget_enabled  boolean not null default true,
  monthly_budget_amount   numeric(14, 2) not null default 30000 check (monthly_budget_amount >= 0),
  start_day_of_month      integer not null default 1 check (start_day_of_month between 1 and 28)
);

-- ── Integrity triggers ────────────────────────────────────────────────────────

-- Keep updated_at honest and make id / owner / created_at immutable.
create or replace function public.protect_transaction_row()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.id := old.id;
  new.user_id := old.user_id;
  new.created_at := old.created_at;
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists transactions_protect on public.transactions;
create trigger transactions_protect
  before update on public.transactions
  for each row execute function public.protect_transaction_row();

create or replace function public.protect_category_row()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.id := old.id;
  new.user_id := old.user_id;
  new.type := old.type;          -- changing type would orphan its transactions' meaning
  new.created_at := old.created_at;
  return new;
end;
$$;

drop trigger if exists categories_protect on public.categories;
create trigger categories_protect
  before update on public.categories
  for each row execute function public.protect_category_row();

-- ── Row Level Security ────────────────────────────────────────────────────────

alter table public.categories   enable row level security;
alter table public.transactions enable row level security;
alter table public.settings     enable row level security;

-- No access for anonymous (not signed-in) requests, even if a policy is added by mistake.
revoke all on public.categories, public.transactions, public.settings from anon;
grant select, insert, update, delete on public.categories, public.transactions, public.settings to authenticated;

do $$
declare t text;
begin
  foreach t in array array['categories', 'transactions', 'settings'] loop
    execute format('drop policy if exists "own rows: select" on public.%I', t);
    execute format('drop policy if exists "own rows: insert" on public.%I', t);
    execute format('drop policy if exists "own rows: update" on public.%I', t);
    execute format('drop policy if exists "own rows: delete" on public.%I', t);

    execute format('create policy "own rows: select" on public.%I for select to authenticated using ((select auth.uid()) = user_id)', t);
    execute format('create policy "own rows: insert" on public.%I for insert to authenticated with check ((select auth.uid()) = user_id)', t);
    execute format('create policy "own rows: update" on public.%I for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id)', t);
    execute format('create policy "own rows: delete" on public.%I for delete to authenticated using ((select auth.uid()) = user_id)', t);
  end loop;
end;
$$;

-- ── Default data for new users ────────────────────────────────────────────────

create or replace function public.seed_user_defaults(uid uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.settings (user_id) values (uid) on conflict (user_id) do nothing;

  if not exists (select 1 from public.categories where user_id = uid) then
    insert into public.categories (user_id, type, name, icon, color, sort_order) values
      (uid, 'income',  'เงินเดือน',        '💼', '#22c55e', 0),
      (uid, 'income',  'รายได้เสริม',      '💡', '#16a34a', 1),
      (uid, 'income',  'ดอกเบี้ย/ปันผล',   '📈', '#15803d', 2),
      (uid, 'income',  'อื่นๆ (รายรับ)',    '➕', '#4ade80', 3),
      (uid, 'expense', 'อาหาร',            '🍜', '#ef4444', 0),
      (uid, 'expense', 'ที่พัก/ค่าเช่า',    '🏠', '#dc2626', 1),
      (uid, 'expense', 'เดินทาง',          '🚗', '#f97316', 2),
      (uid, 'expense', 'สาธารณูปโภค',      '💡', '#eab308', 3),
      (uid, 'expense', 'สุขภาพ',           '🏥', '#a855f7', 4),
      (uid, 'expense', 'บันเทิง',          '🎮', '#ec4899', 5),
      (uid, 'expense', 'การศึกษา',         '📚', '#6366f1', 6),
      (uid, 'expense', 'เสื้อผ้า/ของใช้',   '👕', '#0ea5e9', 7),
      (uid, 'expense', 'อื่นๆ (รายจ่าย)',   '➖', '#94a3b8', 8);
  end if;
end;
$$;

-- security definer functions must not be callable through the API
revoke execute on function public.seed_user_defaults(uuid) from public, anon, authenticated;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform public.seed_user_defaults(new.id);
  return new;
end;
$$;

revoke execute on function public.handle_new_user() from public, anon, authenticated;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();
